[project]
name = "livekit-bot"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "livekit-agents[openai]~=1.2",
    "livekit-plugins-noise-cancellation~=0.2",
    "python-dotenv>=1.1.1",
]
